FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache python3 make g++ git linux-headers libudev-dev eudev-dev
ENV NODE_ENV=production
ENV SKIP_USB_BUILD=1
ENV BUILD_USB=0
ENV NODE_OPTIONS=--openssl-legacy-provider
COPY package.json ./
RUN npm install --no-optional --force
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
